### ISSUE TITLE
[iOS] Support info - Contact support

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-ios#118]
User can access support email from profile page to get more help using the application.

![2023-12-06 15 05 21](https://github.com/openedx/openedx-app-ios/assets/121940663/14a14aed-42de-4fc4-b1e2-4252275b124a)
Note: Current edX app from store is shown in the attachment

**Comment by marcotuts** [comment]
Can I ask for clarification on the plans for this? I know the support page in the app needs to be added but edXpert seems like it is separate from this is that true? The edX app has a "submit feedback" page / email the support team section separate from edXpert.

**Comment by moiz994** [comment]
This functionality is already implemented in the RG app. It can be seen by tapping "Contact support" in the profile screen.

**Comment by saeedbashir** [comment]
The email is configurable already with the config key `FEEDBACK_EMAIL_ADDRESS`. So whatever will be the value in `FEEDBACK_EMAIL_ADDRESS` the email will be sent to that email.
