### ISSUE TITLE
[iOS] Support info - Terms of Service / Privacy Policies

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-ios#120]
The edX Prod App has these links:
* [edx Terms of Service](https://www.edx.org/edx-terms-service/)
* [edX Privacy Policy](https://www.edx.org/edx-privacy-policy)
 
Open these links inside application.

![2023-11-24 15 30 16](https://github.com/openedx/openedx-app-ios/assets/121940663/29d5d006-6820-4bd9-af0f-c18bac6a730e)

**Comment by moiz994** [comment]
FYI: These pages are webview based implementations within the app.

**Comment by moiz994** [comment]
Please note that for these links we should not show the buttons if the corresponding key in the config is empty.
