### ISSUE TITLE
[iOS] Start / Resume course

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-ios#121]
User should be able to start the course. 

User should be able to resume the course. Selecting it, user proceeds to the next assignment to be completed.

The continue button does direct the user to the component.

Web and mobile progress should be in sync. i.e. Mobile learners should be able to continue learning from where they left on the web and vice versa.

![Image](https://github.com/openedx/openedx-app-ios/assets/121940663/e3e47ccc-7fc2-4868-bf5d-87523d629e65)

**Comment by marcotuts** [comment]
This is an odd case, @volodymyr-chekyrta any guesses as to why resume course is missing? 

@nizmaylova  - the start / resume buttons are present in my build of the app currently .

**Comment by volodymyr-chekyrta** [comment]
@nizmaylova 
I noticed from the screenshot that you're using a very old build from the Open edX conference demo. 
Please update to the latest version.

**Comment by khanangrauer** [comment]
Update similar to prod edX app - where continue moves to content directly. 

@volodymyr-chekyrta I don't see this button on iOS in develop branch. Is there something I need to do?

**Comment by volodymyr-chekyrta** [comment]
Here's a quick demo on how to find this button. 
https://github.com/openedx/openedx-app-ios/assets/127732735/faa4a610-c4da-4abf-b813-20e5559007dd
Here is the source code:
https://github.com/openedx/openedx-app-ios/blob/main/Course/Course/Presentation/Outline/CourseOutlineView.swift#L95-L119

@khanangrauer Could you check if this feature's turned on in your Open edX instance?

**Comment by moiz994** [comment]
@marcotuts @touchapp  I think there's no active development being done on this issue, should we move it back to Discover/Product Definition?

**Comment by moiz994** [comment]
More info shared by @miankhalid on this issue. 

- The continue button does direct the user to the component. 
- Web and mobile progress should be in sync. i.e. Mobile learners should be able to continue learning from where they left on the web and vice versa. 

Axinite team taking up this work.
