### ISSUE TITLE
[iOS] Build System for Custom Application Configuration

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#146]
Shared package structure / repository for loading in pre-build configuration / overrides that would make keeping brand specific requirements out of the core mobile repositories

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-app-ios/issues/151
```

**Comment by marcotuts** [comment]
From discussion, suggestion to use python based configuration repo / tool to help populate assets / configuration / etc.

**Comment by nizmaylova** [comment]
Subtask in Android repository : https://github.com/openedx/openedx-app-android/issues/88
