### ISSUE TITLE
[iOS] Move Sequence Units level to Course home view as nested list

### ISSUE THREAD

**Issue by sergeymomot** [openedx/openedx-app-ios#155]
Right now Course Sequence units are opens on separate page:
<img width="280" alt="or281520642-3ca96add-aa5f-4319-b8f0-2ecd821f9f5e" src="https://github.com/openedx/openedx-app-ios/assets/2964930/1c580ab7-f008-41fd-959f-e04951358237">

we need to get rid of this separate page and move Sequence units to Course home view as nested list:
<img width="280" alt="281520985-8804e966-432c-4575-8175-e85d28846e2a" src="https://github.com/openedx/openedx-app-ios/assets/2964930/418a0ca8-20f6-4fa2-b7e1-4eb9c0c4657f">

so that Sequence units list appears/disappears as nested list when user tap on Course Sequence name:
<img width="280" alt="281521737-0ffb5292-ddc5-4b49-9b94-af5943394005" src="https://github.com/openedx/openedx-app-ios/assets/2964930/3cf5087b-1682-42ea-841e-7c0449f70028">

**Comment by marcotuts** [comment]
Hi! - this is not the expected future direction, the ticket should not be completed as defined. FYI @sergeymomot

**Comment by marcotuts** [comment]
@sdaitzman - fyi on another area of design definition

**Comment by marcotuts** [comment]
No we didn't discuss this before, not sure what other item other than the resume course button logic being cleaned up we discussed before. 

Adding a third tier of hierarchy to the course outline page I don't remember ever discussing or seeing proposed before

**Comment by moiz994** [comment]
@touchapp this was mentioned in yesterday's meeting so I was reviewing it and I see that the implementation logic is a little off as compared to the prod edX app. The dropdown/accordion should be on the section level of the course but in this implementation, it is on the sub-section level. 

I think that's what @marcotuts means by:
> Adding a third tier of hierarchy to the course outline page I don't remember ever discussing or seeing proposed before

Below are some screenshots that can help in spotting the difference.

|Prod App  | Current Work |
| ------------- | ------------- |
|<img src="https://github.com/openedx/openedx-app-ios/assets/109789173/8a91359e-6099-4d43-b145-767b1c5c1832" width="400">|<img width="400" alt="Screenshot 2023-12-05 at 11 24 35 AM" src="https://github.com/openedx/openedx-app-ios/assets/109789173/707f9f0f-5491-4f0b-9c3d-c2a90a1f9183">|

**Comment by touchapp** [comment]
Hey @moiz994 we don't have a requirement to directly copy the prod edx app. What we are doing is adding functionality that exists on the prod app. They won't look exactly the same.

**Comment by moiz994** [comment]
It's not about the looks but the implemented functionality is not matching the functionality. We've added three levels of course hierarchy on this page but it should be just the first two. Check out where the accordion sits in both images.

**Comment by touchapp** [comment]
@moiz994 yes, you're right. I discussed this with Eugene and Poornima. The functionality will be updated. Thanks for the call-out. 

cc @eyatsenkoperpetio

**Comment by marcotuts** [comment]
I don't know the exact goals on the edX side for this navigation, but this change is not one I would recommend merging into the experience - our goal with navigation updates is to remove navigational complexity and we believe we will have a path to eliminate the section unit listing page (as described in the issue above) but the solution we have in mind does not add this content to the course home page / outline.
