### ISSUE TITLE
[iOS] Assessment content

### ISSUE THREAD

**Issue by nizmaylova** [openedx/openedx-app-ios#179]
Add Assessment content support  in the mobile app.

[Link to content](https://learning-raccoonapis.sandbox.edx.org/course/course-v1:edx+DW101+2023_DW/block-v1:edx+DW101+2023_DW+type@sequential+block@1e5cd9f233a2453f83731ccbd863b731/block-v1:edx+DW101+2023_DW+type@vertical+block@f467da80028f4f83b35707e873edfe88)

**Comment by moiz994** [comment]
Implemented through webview in the Discover tab. Closing ticket.
