### ISSUE TITLE
[iOS] Add ability to open and download currently unsupported videos

### ISSUE THREAD

**Issue by sergeymomot** [openedx/openedx-app-ios#229]
Some [videos](https://learning-raccoonapis.sandbox.edx.org/course/course-v1:edx+DW102+2023_DW/block-v1:edx+DW102+2023_DW+type@sequential+block@bcd7d5cbf39942fcb36eadde3c80a1a9) are not open in the app (only “Open in browser” button is shown)
<img width="280" alt="fde0bbe3-b750-4eab-a652-6bfad3f77816" src="https://github.com/openedx/openedx-app-ios/assets/2964930/fde0bbe3-b750-4eab-a652-6bfad3f77816">

We need:
- find out the reason why these videos are not open
- find out how to download this content for offline mode

**Comment by marcotuts** [comment]
There are some videos that can't be downloaded based on format - one example is Youtube videos / embedded videos like that. fyi @nizmaylova

**Comment by marcotuts** [comment]
Some other videos can be configured to be unavailable on mobile entirely, so those won't be able to be viewed or downloaded. there is a "view on mobile" configuration field that is now respected / used in the app based on a PR. Educators can decide if a video isn't available in this way.
