### ISSUE TITLE
[iOS] UI issue in Dark mode on "Dates" tab

### ISSUE THREAD

**Issue by sergeymomot** [openedx/openedx-app-ios#241]
In Dark mode on "Dates" tab some of the text is almost invisible

<img width="580" alt="ca4ddba7-e623-4e71-9f8d-77fe2ea743bf" src="https://github.com/openedx/openedx-app-ios/assets/2964930/ca4ddba7-e623-4e71-9f8d-77fe2ea743bf">

**Comment by moiz994** [comment]
Thank you, @shafqat-muneer. 
@sergeymomot I'm closing this issue.
