### ISSUE TITLE
[iOS] Q1 2024 - Misc Bugs / Cleanup

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#252]
CLOSING AS DUPLICATE

Quarterly ticket (for Q1 2024) to group iOS tickets as an epic label.
This is a way to organize misc bugs and cleanup tasks that have otherwise no epic / home to associate them with and thus aren't represented on the roadmap.

```[tasklist]
### Tasks
```

**Comment by marcotuts** [comment]
@rnr  - I have added these two tickets above to a Q1 ticket so we can close the Q4 iOS bug epic, thanks for tracking all this work!

**Comment by rnr** [comment]
@marcotuts  - I think we have one already
https://github.com/openedx/openedx-app-ios/issues/226

**Comment by marcotuts** [comment]
Thanks! I'm unlinking the tickets and closing this as a duplicate I see now.
