### ISSUE TITLE
[iOS] Make course menu items more bright

### ISSUE THREAD

**Issue by sergeymomot** [openedx/openedx-app-ios#257]
Right now course menu items appear as if they are inactive (as if they cannot be clicked), need to make course menu items more bright
<img width="280" alt="628b78e1-f069-4e27-9707-fdaab0b52798" src="https://github.com/openedx/openedx-app-ios/assets/2964930/628b78e1-f069-4e27-9707-fdaab0b52798">

Comparison with existing edX app:
<img width="280" alt="240a025f-cb60-4564-a0bf-351542a8680c" src="https://github.com/openedx/openedx-app-ios/assets/2964930/240a025f-cb60-4564-a0bf-351542a8680c">

**Comment by rnr** [comment]
@moiz994 unselected menu items look a little 'disabled'. Should we use some other grey color for it? Or confirm it's ok and we will close this issue.
Thank you

**Comment by moiz994** [comment]
@rnr true, they do look disabled. Is there any other appropriate color in the color palette? If not, let's do some quick hit and trial.
