### ISSUE TITLE
[iOS] Align "Back to profile" button title

### ISSUE THREAD

**Issue by sergeymomot** [openedx/openedx-app-ios#315]
Open Profile -> Edit -> tap Delete account -> observe "Back to profile" button: button name is moved down.
This issue applies to iPhone and iPad. 
<img width="230" alt="064542c8-505f-4809-9751-1c2cd7b2004a" src="https://github.com/openedx/openedx-app-ios/assets/2964930/064542c8-505f-4809-9751-1c2cd7b2004a">

<img width="380" alt="c40c4aed-f5f2-4481-948a-bcc0494aee50" src="https://github.com/openedx/openedx-app-ios/assets/2964930/c40c4aed-f5f2-4481-948a-bcc0494aee50">

Need to align the button title

As a possible solution - we can simply remove this button, since at the top left there is a "Back" button that performs the same action

**Comment by rnr** [comment]
Hello @sdaitzman 
Are you ok if we get rid this button or it's needed for some design purposes?
Thank you

**Comment by sdaitzman** [comment]
Hi @rnr, thank you for tagging me to check about this. I think it would be preferable to keep the Back to Profile button if possible.

From a design standpoint, screens that allow a destructive action should include a quick and clear default action to opt out of that destructive action. It's not a frequent situation, but e.g. if a user has entered their password but realized that they do not want to delete their account, it should be clear that the default action is to go back without deleting their account.

On this screen, I also think the Delete Account button should eventually use the red error/danger color with an outlined (secondary) button style, and the Back to Profile button should use the primary button style. This would emphasize which action is destructive. Those changes may fall under some future design enhancements within account settings/profile.
