### ISSUE TITLE
Learn Page: Listing vs NextStep mode

### ISSUE THREAD

**Issue by marcotuts** [openedx/openedx-app-ios#321]
This increment also introduces modes for the product view (listing - status quo) and (next step - future direction). The default view will shift to being ‘next step’ however it will be easy for applications to configure the listing view instead for courses.

The Next step mode will introduce card types: Primary Cards, Basic Cards, Progress Cards

Primary Cards - Currently only 1 is shown on the Learn page (Courses mode), with optional messages shown (documented in Confluence)

Basic Cards - Showing 10 of these under the primary card with a "View All" item at the end of the list. (For tablets show only 7 cards before View All item) 

Progress Cards - Shown on the (all) My Courses view in 2x2 grid for phones. Similar to basic cards plus the addition of course date details and progress .

This mode will allow app users to keep using the listing cards as they exist for now as the non-default option for the Learn page. We may consider removal of this option in the future but keeping it in for now.

**Comment by moiz994** [comment]
@marcotuts can you please share the confluence page related to this ticket?
