### ISSUE TITLE
[iOS] Full screen loader whille course is upgarding

### ISSUE THREAD

**Issue by moiz994** [openedx/openedx-app-ios#405]
While implementing IAP on the legacy apps, it was seen that after processing the payments it takes some time for the course to upgrade. Considering design heuristics and for a more interactive approach, we have implemented a full-screen loader to show while the learners wait for their course to be upgraded. 

Acceptance criteria:
- The loader shows up after the payment is processed and the backend is unlocking the course content
- The loader is not shown when upgrading is completed
- The loader illustration should either be generic or should go with the theme of the app 

Current implementation: 
[Video Demo](https://drive.google.com/file/d/1Gc20gkxsRIjkBdiiG_RdtiH4ufFSREMl/view?usp=drive_link)

<img width="288" alt="Screenshot 2024-04-19 at 1 45 49 PM" src="https://github.com/openedx/openedx-app-android/assets/109789173/f11c1c07-b203-4c81-b0d4-8d074f33aa1a">

**Comment by moiz994** [comment]
@forgotvas @saeedbashir  we need to update the rocket illustration to the following rocket icon in order to match the schema design system.

  https://fonts.google.com/icons?selected=Material+Symbols+Outlined:rocket_launch:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=rocket&icon.size=24&icon.color=%235f6368



![Image](https://github.com/openedx/openedx-app-android/assets/109789173/d22e0be5-fe44-4d08-a4e3-383b402c6212)

**Comment by forgotvas** [comment]
@moiz994, like this?
[rocket_launch_24dp_FILL0_wght400_GRAD0_opsz24.pdf](https://github.com/user-attachments/files/15789703/rocket_launch_24dp_FILL0_wght400_GRAD0_opsz24.pdf)

**Comment by moiz994** [comment]
@forgotvas is it possible to reduce the stroke on the rocket?

**Comment by forgotvas** [comment]
@moiz994 

Dark | Light
--|--
![Simulator Screenshot - iPhone 15 - 2024-06-12 at 12 15 35](https://github.com/openedx/openedx-app-ios/assets/480059/5fb34d63-29bf-44e8-b304-6d26021919d3)|![Simulator Screenshot - iPhone 15 - 2024-06-12 at 12 15 27](https://github.com/openedx/openedx-app-ios/assets/480059/61fcfd98-086b-4736-939e-f555ecb78fcb)

**Comment by moiz994** [comment]
@forgotvas thanks, the stroke looks better but lets get some advice from the design team. 

@sdaitzman & @ekangedx can you guys share some design input here? Since the schema design system does not have the illustrations we're trying to add material design icons to match up with the design system. What do you think the screen should look like?

**Comment by sdaitzman** [comment]
Hi @moiz994, I wonder if we can implement something similar to the [limited course states](https://www.figma.com/design/iZ56YMjbRMShCCDxqrqRrR/Open-edX-Mobile-App-All-Screens-v2.1?node-id=10061-77377&t=lzmFyrV31lusEWoK-4) graphics using the `rocket_launch` Material Design icon?
![image](https://github.com/openedx/openedx-app-ios/assets/1499476/01d4ac60-bc18-45b3-9c03-566f3c9960cd)

**Comment by moiz994** [comment]
@sdaitzman looking at this, I think we can reduce the icon and text size. The order imo should be rocket, text, loader.

**Comment by moiz994** [comment]
@sdaitzman looking at all the possible places where learners can upgrade and the flow, we can not show the course header like the limited course states for now. 

Here's a quick design by me that I think we can use for now:



![Image](https://github.com/openedx/openedx-app-ios/assets/109789173/97572432-9513-438c-afe0-47395a04e24e)

@forgotvas please have a look at the above loading screen and let me know if there are any questions.

**Comment by forgotvas** [comment]
hi, @moiz994, what about horizontal mode? What do you like?
1 | 2
--|--
![Simulator Screenshot - iPhone 15 - 2024-06-24 at 21 04 56](https://github.com/openedx/openedx-app-ios/assets/480059/2cd3a35b-1b4e-4312-8560-7175ac8d4932)|![Simulator Screenshot - iPhone 15 - 2024-06-24 at 21 06 31](https://github.com/openedx/openedx-app-ios/assets/480059/aa087c2f-3629-43ea-a35e-24f7e7e17739)

**Comment by moiz994** [comment]
2 looks good! 👏🏻
