### ISSUE TITLE
[iOS] Add upgrade banner in the FC47 Primary Course card view

### ISSUE THREAD

**Issue by moiz994** [openedx/openedx-app-ios#460]
Based on the changes implemented in FC47, the Learn tab has changed to show a primary course card instead of a course list. We need to incorporate the upgrade banner on the primary course card.

**Example UI of new upgrade banner below:**
![image](https://github.com/openedx/openedx-app-ios/assets/109789173/7d441169-7022-453e-bf3d-d9bba429f48a)

Copy of upgrade button should be the same as the current upgrade banner which is "Upgrade to access more features".
Icon to replace the lock icon: https://www.figma.com/design/iZ56YMjbRMShCCDxqrqRrR/Open-edX-Mobile-App-All-Screens-v2.1?node-id=14959-174213&t=UtbU6epvpSMhxkYJ-4

There's an example of the primary course card with that icon in Figma [here](https://www.figma.com/design/iZ56YMjbRMShCCDxqrqRrR/Open-edX-Mobile-App-All-Screens-v2.1?node-id=16445-355149&t=fuhXG7UueUtJxFBM-11).

![image](https://github.com/openedx/openedx-app-ios/assets/109789173/45106efa-d784-4407-bd52-a75fb6838095)

**Comment by forgotvas** [comment]
hi @moiz994, should we add icons to small course items too?

![Screenshot 2024-07-05 at 20 58 06](https://github.com/openedx/openedx-app-ios/assets/480059/2fc39186-afa2-4021-9bfc-39f6de352423)

**Comment by moiz994** [comment]
We can do this post MVP. We'll have to confirm all the logic that goes behind showing a specific icon.

**Comment by forgotvas** [comment]
@moiz994 is that ok?
![Simulator Screenshot - iPhone 15 - 2024-07-11 at 17 35 42](https://github.com/openedx/openedx-app-ios/assets/480059/49e99a18-29e6-4c7c-9031-a7e844fcb5f9)

**Comment by moiz994** [comment]
is it just me or does the trophy look bigger than the other icons in the buttons?

**Comment by moiz994** [comment]
another thing I noticed just now is that it would be better if we could use an outline version of the trophy icon instead of the filled icon 

![emoji_events_24dp_000000_FILL0_wght400_GRAD0_opsz24](https://github.com/user-attachments/assets/ab303254-aebb-49d4-bd09-ba153291a52a)

**Comment by forgotvas** [comment]
![Simulator Screenshot - iPhone 15 - 2024-07-12 at 12 54 33](https://github.com/user-attachments/assets/0ea842d8-ac07-4653-a4ba-e2238908285d)

**Comment by moiz994** [comment]
I think this looks good. Just kindly verify the icon size matches the other icons.

**Comment by forgotvas** [comment]
Merged to `2u/develop`
