### ISSUE TITLE
[iOS] There is no "Upgrade..." button for the course

### ISSUE THREAD

**Issue by sergeymomot** [openedx/openedx-app-ios#488]
Found that for the course https://learning.edx.org/course/course-v1:HarvardX+MCB63X+1T2024c/home in OpenedX mobile app there is no "Upgrade to access more features button". At the same time this button is present on the Web and edX mobile app

![Image](https://github.com/openedx/openedx-app-ios/assets/2964930/bc1f6ded-1371-4776-a5a3-2001e5cc6e93)

**Comment by rnr** [comment]
closed 
bug is on current edx app

**Comment by forgotvas** [comment]
old app uses
```
if let courseModes = dictionary["course_modes"] as? [[String: AnyObject]]  {
            for mode in courseModes where mode["slug"] as? String == "verified" {
                verifiedModeAvailable = true
                if let sku = mode["ios_sku"] as? String {
                    iosSku = sku
                }
                lmsPrice = mode["min_price"] as? Double ?? 0
                break
            }
        }
```

verifiedModeAvailable isn't checking for the sku which it should be
